name: rsudp
channels:
  - defaults
  - rpi
  - conda-forge
dependencies:
  - python==3.7.4
  - pip==20.0.2
  - matplotlib==3.1.1
  - numpy==1.16.4
  - future
  - scipy
  - lxml
  - sqlalchemy
  - obspy
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - attrs==19.3.0
    - multidict==4.7.4
    - oauthlib==3.1.0
    - pydub==0.23.1
    - requests-oauthlib==1.3.0
    - telepot==12.7
    - twython==3.7.0
    - urllib3==1.24.2
    - yarl==1.4.2
    - rsudp
